# -*- coding: utf-8 -*-
"""Logistic_regression_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i85a0bw-GpZBefK8ony0KtPlvD9OXVPR

Import required packages
"""

# Import Required packages 
#-------------------------

# Import the Logistic Regression Module from Scikit Learn
from sklearn.linear_model import LogisticRegression  

# Import the IRIS Dataset to be used in this Kernel
from sklearn.datasets import load_iris  

# Load the Module to split the Dataset into Train & Test 
from sklearn.model_selection import train_test_split

"""Load the IRIS Data"""

# Load the data
Iris_data = load_iris()

"""Split the IRIS Data into Training & Testing Data"""

#Split data
Xtrain, Xtest, Ytrain, Ytest = train_test_split(Iris_data.data, Iris_data.target, test_size=0.3, random_state=4)

# Define the Model
LR_Model = LogisticRegression(C=0.1, max_iter=20, fit_intercept=True, n_jobs=3, solver='liblinear')

# Train the Model
LR_Model.fit(Xtrain, Ytrain)

